### ISSUE TITLE
¿Did someone test this before shipping?

### ISSUE THREAD

**Issue by tobeorla** [OmarGM2294/phonegap_simple_vuejs#1]
I see around basic errors like:
https://github.com/OmarGM2294/phonegap_simple_vuejs/blob/master/template_src/www/src/App.vue#L3

```html
<router-view><router-view>
```

```html
<router-view></router-view>
```

And errors like:
```
 Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
          <Root>
```

¿Did someone test this?

**Comment by OmarGM2294** [comment]
Hi, you are completly right, i will fix it, i tested it in 15 different computers and there was no errors. Can you please tell exactly where was the error to fix it?. Thanks, have a nice day

**Comment by tobeorla** [comment]
Running `npm run build && phonegap serve` & opening the website in Chrome (the only change that was made to the code was that router-view fix)

**Comment by OmarGM2294** [comment]
Normaly this happens when the import doesn't work, but with babel this problem is fixed, other thing could be a syntax error. Did you install all dependencies?, Did you make changes to anything?. I know that the only changes was the router-view, be patience please, your feedback is important to make this template good enough for all of us. Have a nice day.
